from draw import (
    RED, GREEN, BLUE, BLACK, GREY, WHITE, YELLOW, MAGENTA, CYAN, ORANGE, GOLD, PINK, DEEPPINK, ORCHID, MAROON,
    DARKVIOLET, PURPLE, TURQUOISE, SKYBLUE, TAN, CHOCOLATE, BROWN
)
from device_input import (
    NUMBER_OF_MOUSE_BUTTONS, NUMBER_OF_KEYBOARD_BUTTONS,
    MOUSE_PRIMARY, MOUSE_MIDDLE, MOUSE_SECONDARY, MOUSE_BACK, MOUSE_FORWARD
)
from collision import *
